### ISSUE TITLE
Can't wipe free space on removable storage

### ISSUE THREAD

**Issue by ali-oem** [R3nt0n/wiper#1]
![Screenshot from 2021-02-02 20 36 32](https://user-images.githubusercontent.com/71282548/106653205-c6d0bb00-6596-11eb-8b53-c9c071dd483a.png)
I've tried to wipe my external storage drive but got this error.
Using Ubuntu 18.04

**Comment by r3nt0n** [comment]
Hi @ali-oem !

After implementing overwrite method selection for all features, i forgot to update `wipe_free_space` call to add the `method` parameter. The last commit should fix it.

Thank you :+1:
