### ISSUE TITLE
doesn't recognize windows files

### ISSUE THREAD

**Issue by GuiTaek** [R3nt0n/wiper#2]
Whenever you try to save delete a windows file, the following error message is shown:
```
  ←[91m[!]←[0m ERROR: No files found
```
I guess you don't support Windows? Would  be nice to mention it in the readme.md.

How to reproduce:

cd in terminal to folder

create a file `test` in that folder

type in:
```
python path\to\wiper\wiper.py -p ./test
```
or
```
python \path\to\wiper\wiper.py -p .\test
```
or
```
python \path\to\wiper\wiper.py -p test
```
or
```
python \path\to\wiper\wiper.py -p \path\to\file
```
everything give the same error message

**Comment by r3nt0n** [comment]
Hi,

It should work on Windows. I assume that you are running it with Python 3. It's most likely a path issue. The relative path starts from the script location, so:

+ If you want to provide a relative path to the file, you should change your current working directory to the script folder and run it like `python3 wiper.py <relative-path-to-file>`
+ Or run the script from wherever you want and provide an absolute path to the file you want to wipe.

PS: Please, be nice, remember that this tool is a free contribution.

**Comment by GuiTaek** [comment]
Hi,

of course I'm aware that you do it in your free time it wasn't a demand more a comment as I think mentioning that a kernel isn't supported isn't a lot of work. If windows is supported and I get it to work then I'm willing to contribute to readme.md what I think would have saved me a lot of time in the first place.

Indeed, I used the latest version of Python 3, as stated in the dependencies.

I tried relative path, absolute path, paths with /-es, paths with \-es, paths with \\-es

and I cd-ed to the file I wanted to delete.

I even tried your interactive tool.

What does mean PD? I have found nothing on google that helped me.

Looking into the code didn't helped either as you don't use the usual sys library, which is the only one I feel comfortable.

I put a lot of work into getting this to run and maybe that's the reason I was a little bit harsh, I'm sorry, if you felt not be treated nice.

**Comment by r3nt0n** [comment]
Okay, no problem, thanks for your answer :)

Have you tried cd to the script path and run it from there (like `python wiper.py <whatever>`? maybe it could be a problem while importing the libraries (the ones in r3ntlib). Sorry, currently I dont have a fast way to test it on a Windows environment.

(PD was a mistake, I meant PS)

**Comment by GuiTaek** [comment]
I have the following session:
```
Microsoft Windows [Version 10.0.19045.2364]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\wiper>git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        temp

nothing added to commit but untracked files present (use "git add" to track)

C:\wiper>git pull
Already up to date.

C:\wiper>python wiper.py -p temp
  ←[91m[!]←[0m ERROR: No files found

C:\wiper>
```

Edit: I don't know why I was so dump 2 days ago. It wasn't that hard to debug it. So applying (e.g. with git apply /path/to/patch) following patch (or applying manually)

```
diff --git a/r3ntlib/os_ops.py b/r3ntlib/os_ops.py
index 2eed5b8..db52536 100644
--- a/r3ntlib/os_ops.py
+++ b/r3ntlib/os_ops.py
@@ -33,6 +33,12 @@ def find_files(root_path, files_to_exclude=()):
        files_to_exclude -- (optional) list of absolute path to files that will
                            be excluded from the return list
     """
+    if os.path.isfile(root_path):
+        root_path = os.path.abspath(root_path)
+        if root_path in files_to_exclude:
+            return []
+        return [root_path]
+    
     files_list = []
     for root, dirs, files in os.walk(root_path, topdown=False):
         for name in files:
diff --git a/wiper.py b/wiper.py
index bceb1cd..cde63cf 100644
--- a/wiper.py
+++ b/wiper.py
@@ -174,7 +174,7 @@ def wipe(path, method='r', exclude_script=True):
         # Get actual script absolute path to exclude from deletion task
         script_abspath = os.path.abspath(__file__)
         # Get all files included in the given path
-        files_to_wipe = os_ops.find_files(path, script_abspath)
+        files_to_wipe = os_ops.find_files(path, [script_abspath])
     if not files_to_wipe:
         print(u'  {}[!]{} ERROR: No files found'.format(color.RED, color.END))
         status = 2
```
let's it work smoothly. I'm not even sure if the second diff is needed. It works for every described case above so it's just some small case you forgot that the root_path is not a directory but a file. Maybe this is what you didn't understand in my issue description.

If you want, I make a pull request so you just have to merge, if you want that change.

Edit2: Especially it shouldn't work in this particular case in linux, too.

**Comment by r3nt0n** [comment]
Yes, I was reviewing the code and after some debug I arrive exactly to the same point, then came back here and saw your edit :smile: 

I didnt mantain this code for a while and reviewing now I would change a lot of things, but having in mind that these wipes methods dont work on SSDs drives (and are not even recommended because it shortens the lifespan) I didnt see the point to keep updating the tool.

It would be awesome if you want to make the contribution, they are always welcome!

**Comment by GuiTaek** [comment]
> Yes, I was reviewing the code and after some debug I arrive exactly to the same point, then came back here and saw your edit 😄

Haha that's funny, probably because there was just such an easy fix.
> I didnt mantain this code for a while and reviewing now I would change a lot of things,

Haha I know that to well of my projects, too
> but having in mind that these wipes methods dont work on SSDs drives

That's interesting, didn't know that and I have to check if my sensible files are really deleted (haven't used your library as it didn't worked). I read [this](https://www.tomshardware.com/how-to/secure-erase-ssd-or-hard-drive) article multiple times and as far as I understood, it isn't possible to delete single files or folders which means it can't be implemented in your tool. Maybe I could implement a ssd-check using the library [ssd_checker](https://github.com/kipodd/ssd_checker) either by just copying the file into your repo (with mentioning the source of the file) or directly ask the user to pip install -r requirements.txt?

>It would be awesome if you want to make the contribution, they are always welcome!

Then I do my best to make helpful pull requests! Thanks for the possiblity to participate!

**Comment by r3nt0n** [comment]
> Haha that's funny, probably because there was just such an easy fix.

Well, is always harder to debug code that you didnt write, so I think it has much more merit on your side :+1: 

> I read [this](https://www.tomshardware.com/how-to/secure-erase-ssd-or-hard-drive) article multiple times and as far as I understood, it isn't possible to delete single files or folders which means it can't be implemented in your tool.

That's right, the only way to do it with this tool would be to first delete the files and then use the wipe free space mode, which would be able to successfully wipe the deleted files and shouldnt be recoverable.

> Maybe I could implement a ssd-check using the library [ssd_checker](https://github.com/kipodd/ssd_checker) either by just copying the file into your repo (with mentioning the source of the file) or directly ask the user to pip install -r requirements.txt?

That's clever, we could check first if the path provided is inside an SSD drive, and only continue with execution if it return False. Regarding your question, I think the better way would be to incorporate the module as a dependency in the `requirements.txt`.

> Then I do my best to make helpful pull requests! Thanks for the possiblity to participate!

Glad to hear that! I will wait for your pull request to incorporate these two proposals, so you will appear as a contributor :)

**Comment by GuiTaek** [comment]
> Well, is always harder to debug code that you didnt write, so I think it has much more merit on your side 👍

I think it's this time different as this is code that you haven't touched a long time. For that holds the same rule as for code you didn't write. I think, the merit is equally. I just happen to be a little bit faster.

> That's right, the only way to do it with this tool would be to first delete the files and then use the wipe free space mode, which would be able to successfully wipe the deleted files and shouldnt be recoverable.

Is there any possibility to target only single files?

>That's clever,

Thanks

> we could check first if the path provided is inside an SSD drive, and only continue with execution if it return False.

Ok, I'll do that. I also suggest a warning inside readme, so future user have saved some time. And maybe we create another issue to talk further about that there? I really liked this message from you and this will be closed when you merge.

> Regarding your question, I think the better way would be to incorporate the module as a dependency in the requirements.txt.

I'm happy that you say this, I was really unsure about that as it makes it more work to use but I guess safety first.

> Glad to hear that! I will wait for your pull request to incorporate these two proposals, so you will appear as a contributor :)

It is an honor. It's my second code contribution to open source.
